spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 15242635
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
api:
  prefix: /api/v1